### ISSUE TITLE
Release AAR files do not appear to contain any compiled code

### ISSUE THREAD

**Issue by sirnuke** [wshunli/android-copy-assets#1]
I was checking out this library, but had trouble importing import com.wshunli.assets.CopyAssets;

Upon further review, the AAR archives uploaded to jcenter don't appear to have any classes - the included classes.jar is an empty ZIP.

**Comment by wshunli** [comment]
My mistake.
This bug has been fixed in version 2.2.0.
Thanks for reporting this.
